name: Build and Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js for Angular build
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build Angular app
      - name: Build Angular
        run: npm run build -- --configuration production

      # 5. Log in to Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # 6. Build and push Docker image (Nginx only)
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-app:latest  .
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/angular-app:latest

      # 7. Deploy to Ubuntu server via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/angular-app:latest
            sudo docker stop angular-container || true
            sudo docker rm angular-container || true
            sudo docker run -d -p 4200:4200 --name angular-container ${{ secrets.DOCKER_USERNAME }}/angular-app:latest
